# Generated by Django 2.2 on 2023-08-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230724_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
