# Generated by Django 2.2 on 2023-08-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='available',
            new_name='availability',
        ),
    ]
