# Generated by Django 2.2 on 2023-08-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230804_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='availability',
        ),
    ]
