# Generated by Django 2.2 on 2023-08-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_products_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
