# Generated by Django 2.2 on 2023-08-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='availability',
            new_name='avail',
        ),
    ]
