# Generated by Django 2.2 on 2023-08-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20230804_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='accessable_prodts',
        ),
    ]
