# Generated by Django 2.2 on 2023-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_products_accessable_prodts'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='text',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
