# Generated by Django 2.2 on 2023-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_products_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='accessable_prodts',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
