# Generated by Django 2.2 on 2023-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_products_accessable_prodts'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nme', models.TextField(max_length=100)),
            ],
        ),
    ]
