# Generated by Django 2.2 on 2023-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='text',
        ),
        migrations.AlterField(
            model_name='products',
            name='accessable_prodts',
            field=models.BooleanField(default=True),
        ),
    ]
