# Generated by Django 2.2 on 2023-08-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20230804_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
